name: Summarize Git Diff on Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Send Git diff to summarizer
        run: python scripts/extract_diff.py
        env:
          SUMMARIZER_URL: https://gitchangesummary.onrender.com/summarize
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          
